# Generated by Django 5.2.3 on 2025-07-02 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='habitlog',
            name='completed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='habitlog',
            name='habit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.habit'),
        ),
    ]
