# Generated by Django 5.2.3 on 2025-07-02 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_habit_archived_alter_habitlog_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitlog',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
